// The nine purchased cast characters as text grids. Copied verbatim (by script)
// from the design handoff's imported-cast.js; do not hand-edit the grids.
// Only bug.variants.ant / .eatant were normalised mechanically: the converter
// had spilled rows 0-1 one column past w and glued 26 stray dots onto row 4,
// so those six rows were truncated / padded to w.
//
// Variants: 'eat' = mouth open (swap with base every ~200ms while feeding),
// 'flap' = wings / tail / ears moved 1px (idle, ~360ms), 'blink' = eyes closed
// (idle, ~150ms every ~3.2s), 'ant' / 'eatant' = the bug's antenna wiggle.
import type { Species } from '../pet/types'
import type { Grid, Palette } from '../components/pixel'

export type CastName = 'bug' | 'angel' | 'dragonet' | 'tanuki' | 'elf' | 'oni' | 'plain' | 'bee' | 'cow'
export type CastVariant = 'eat' | 'flap' | 'blink' | 'ant' | 'eatant'

export interface CastSprite {
  w: number
  h: number
  pal: Record<string, string>
  grid: string[]
  variants: Partial<Record<CastVariant, string[]>>
}

/** Compile-time guard: the cast names and the on-chain Species union must stay identical. */
type Equals<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false
export const CAST_MATCHES_SPECIES: Equals<CastName, Species> = true

export const CAST_NAMES: readonly CastName[] = ['bug', 'angel', 'dragonet', 'tanuki', 'elf', 'oni', 'plain', 'bee', 'cow']
export const CAST_VARIANTS: readonly CastVariant[] = ['eat', 'flap', 'blink', 'ant', 'eatant']

export const CAST: Record<CastName, CastSprite> = {
 "bug": {
  "w": 26,
  "h": 34,
  "pal": {
   "a": "#b63134",
   "b": "#fcdcc0",
   "c": "#e7595e",
   "d": "#f98081",
   "e": "#bb593c",
   "f": "#a28595",
   "g": "#f9b391",
   "h": "#2789aa",
   "i": "#0d2941",
   "j": "#115e7b",
   "k": "#7b1235",
   "l": "#e5dad9",
   "m": "#77352c",
   "n": "#be6769",
   "p": "#c5b5c0",
   "q": "#da836b",
   "r": "#cf7355",
   "M": "#6e3a34"
  },
  "grid": [
   "........................aa",
   ".......................aaa",
   "......................aaa.",
   ".aaaa.................a...",
   "aaa..aa..............n....",
   "........a...........a.....",
   ".........e.........a......",
   "..........a........a......",
   "..........aaaaaaa.a.......",
   ".........aaccddddaa.......",
   "........acccddddddca......",
   ".......acddcdddcdddca.....",
   "......accddadddccddca.....",
   ".....accacgaacggaggaga....",
   ".....accaccagaccaccaca....",
   ".....accabbbbbbbgccaca....",
   ".....aaabbgbbbgbbdddcca...",
   ".....aaabbmbbbmbbdddcca...",
   "....accaggmbbbmggdddack...",
   "....kccaggbbbbbggccckck...",
   "....kcckeebbbbbbrccckk....",
   "..........ijhhhhj.........",
   "...........iihhj..........",
   "...........ihhhj..........",
   "..........ijhhhgj.........",
   "..........igjhjbj.........",
   ".........iibjhjbef........",
   "........fiibbebbelf.......",
   ".......fleibbebbeflf......",
   ".....ff.fegeeeeeelf.ff....",
   "...pl..l.nqbe.ebrf.l..lp..",
   "...f....f.ebe..ebef....f..",
   "....ffff..ebe..ebe.ffff...",
   "...........ee...ee........"
  ],
  "variants": {
   "eat": [
    "........................aa",
    ".......................aaa",
    "......................aaa.",
    ".aaaa.................a...",
    "aaa..aa..............n....",
    "........a...........a.....",
    ".........e.........a......",
    "..........a........a......",
    "..........aaaaaaa.a.......",
    ".........aaccddddaa.......",
    "........acccddddddca......",
    ".......acddcdddcdddca.....",
    "......accddadddccddca.....",
    ".....accacgaacggaggaga....",
    ".....accaccagaccaccaca....",
    ".....accabbbbbbbgccaca....",
    ".....aaabbgbbbgbbdddcca...",
    ".....aaabbmbbbmbbdddcca...",
    "....accaggmbbbmggdddack...",
    "....kccaggbMMMbggccckck...",
    "....kcckeebbMbbbrccckk....",
    "..........ijhhhhj.........",
    "...........iihhj..........",
    "...........ihhhj..........",
    "..........ijhhhgj.........",
    "..........igjhjbj.........",
    ".........iibjhjbef........",
    "........fiibbebbelf.......",
    ".......fleibbebbeflf......",
    ".....ff.fegeeeeeelf.ff....",
    "...pl..l.nqbe.ebrf.l..lp..",
    "...f....f.ebe..ebef....f..",
    "....ffff..ebe..ebe.ffff...",
    "...........ee...ee........"
   ],
   "flap": [
    "........................aa",
    ".......................aaa",
    "......................aaa.",
    ".aaaa.................a...",
    "aaa..aa..............n....",
    "........a...........a.....",
    ".........e.........a......",
    "..........a........a......",
    "..........aaaaaaa.a.......",
    ".........aaccddddaa.......",
    "........acccddddddca......",
    ".......acddcdddcdddca.....",
    "......accddadddccddca.....",
    ".....accacgaacggaggaga....",
    ".....accaccagaccaccaca....",
    ".....accabbbbbbbgccaca....",
    ".....aaabbgbbbgbbdddcca...",
    ".....aaabbmbbbmbbdddcca...",
    "....accaggmbbbmggdddack...",
    "....kccaggbbbbbggccckck...",
    "....kcckeebbbbbbrccckk....",
    "..........ijhhhhj.........",
    "...........iihhj..........",
    "...........ihhhj..........",
    "..........ijhhhgj.........",
    "..........igjhjbjf........",
    "........fiibjhjbelf.......",
    ".......fliibbebbeflf......",
    ".....ff.feibbebbelf.ff....",
    "...pl..l.egeeeeeef.l..lp..",
    "...f....fnqbe.ebr.f....f..",
    "....ffff..ebe..ebe.ffff...",
    "..........ebe..ebe........",
    "...........ee...ee........"
   ],
   "ant": [
    ".........................a",
    "........................aa",
    ".......................aaa",
    "aaaa...................a..",
    "aa..aa................n..a",
    ".......a.............a....",
    "........e...........a.....",
    ".........a..........a.....",
    "..........aaaaaaa.a.......",
    ".........aaccddddaa.......",
    "........acccddddddca......",
    ".......acddcdddcdddca.....",
    "......accddadddccddca.....",
    ".....accacgaacggaggaga....",
    ".....accaccagaccaccaca....",
    ".....accabbbbbbbgccaca....",
    ".....aaabbgbbbgbbdddcca...",
    ".....aaabbmbbbmbbdddcca...",
    "....accaggmbbbmggdddack...",
    "....kccaggbbbbbggccckck...",
    "....kcckeebbbbbbrccckk....",
    "..........ijhhhhj.........",
    "...........iihhj..........",
    "...........ihhhj..........",
    "..........ijhhhgj.........",
    "..........igjhjbj.........",
    ".........iibjhjbef........",
    "........fiibbebbelf.......",
    ".......fleibbebbeflf......",
    ".....ff.fegeeeeeelf.ff....",
    "...pl..l.nqbe.ebrf.l..lp..",
    "...f....f.ebe..ebef....f..",
    "....ffff..ebe..ebe.ffff...",
    "...........ee...ee........"
   ],
   "eatant": [
    ".........................a",
    "........................aa",
    ".......................aaa",
    "aaaa...................a..",
    "aa..aa................n..a",
    ".......a.............a....",
    "........e...........a.....",
    ".........a..........a.....",
    "..........aaaaaaa.a.......",
    ".........aaccddddaa.......",
    "........acccddddddca......",
    ".......acddcdddcdddca.....",
    "......accddadddccddca.....",
    ".....accacgaacggaggaga....",
    ".....accaccagaccaccaca....",
    ".....accabbbbbbbgccaca....",
    ".....aaabbgbbbgbbdddcca...",
    ".....aaabbmbbbmbbdddcca...",
    "....accaggmbbbmggdddack...",
    "....kccaggbMMMbggccckck...",
    "....kcckeebbMbbbrccckk....",
    "..........ijhhhhj.........",
    "...........iihhj..........",
    "...........ihhhj..........",
    "..........ijhhhgj.........",
    "..........igjhjbj.........",
    ".........iibjhjbef........",
    "........fiibbebbelf.......",
    ".......fleibbebbeflf......",
    ".....ff.fegeeeeeelf.ff....",
    "...pl..l.nqbe.ebrf.l..lp..",
    "...f....f.ebe..ebef....f..",
    "....ffff..ebe..ebe.ffff...",
    "...........ee...ee........"
   ]
  }
 },
 "angel": {
  "w": 20,
  "h": 27,
  "pal": {
   "a": "#783814",
   "b": "#ac8c97",
   "c": "#431807",
   "d": "#e3d7d5",
   "e": "#c27550",
   "f": "#721a00",
   "g": "#5e290d",
   "h": "#b15d34",
   "i": "#f1b903",
   "j": "#a9580e",
   "k": "#9c431f",
   "l": "#d79601",
   "m": "#7b6765",
   "n": "#bb6b03"
  },
  "grid": [
   ".....mcccggccmmm....",
   "...cccgajjiiagaac...",
   "..caaaaaaaaaiiaac...",
   "..caaaacccaaaaaagc..",
   "..cgaaaaaacaaaaaggc.",
   ".cggacaagccaaaaangc.",
   "cggaacaagaaaaaaanaac",
   "caaahcaaaaaghaaaaaac",
   "caaaeegaaageehaaaggc",
   "..cgeegeeegeeeakjf..",
   "...fhhgeeeghhekkhf..",
   "...fhjeeeeehhefff...",
   "...bffeeeeeeff.bb...",
   "..bdddffffff..b..b..",
   "..bddddfddhfbbd..b..",
   ".bddddfh..hhfd....b.",
   ".bdbdah....khfd.d.b.",
   ".bdbfhh....kkhf.d.b.",
   "bdfhhf.....feeff.d.b",
   "bdfhhflliiifeefb.b.b",
   "bddffddd...bff..bb.b",
   "bdb.bdd...kkkf...bdb",
   "bdb.b...ffjkkf...bdb",
   "bb..fiia..fiif....bb",
   "....fff....fjf......",
   "....fff....fia......",
   "....ff.....ff......."
  ],
  "variants": {
   "eat": [
    ".....mcccggccmmm....",
    "...cccgajjiiagaac...",
    "..caaaaaaaaaiiaac...",
    "..caaaacccaaaaaagc..",
    "..cgaaaaaacaaaaaggc.",
    ".cggacaagccaaaaangc.",
    "cggaacaagaaaaaaanaac",
    "caaahcaaaaaghaaaaaac",
    "caaaeegaaageehaaaggc",
    "..cgeegeffgeeeakjf..",
    "...fhhgeffghhekkhf..",
    "...fhjeeeeehhefff...",
    "...bffeeeeeeff.bb...",
    "..bdddffffff..b..b..",
    "..bddddfddhfbbd..b..",
    ".bddddfh..hhfd....b.",
    ".bdbdah....khfd.d.b.",
    ".bdbfhh....kkhf.d.b.",
    "bdfhhf.....feeff.d.b",
    "bdfhhflliiifeefb.b.b",
    "bddffddd...bff..bb.b",
    "bdb.bdd...kkkf...bdb",
    "bdb.b...ffjkkf...bdb",
    "bb..fiia..fiif....bb",
    "....fff....fjf......",
    "....fff....fia......",
    "....ff.....ff......."
   ],
   "flap": [
    ".....mcccggccmmm....",
    "...cccgajjiiagaac...",
    "..caaaaaaaaaiiaac...",
    "..caaaacccaaaaaagc..",
    "..cgaaaaaacaaaaaggc.",
    ".cggacaagccaaaaangc.",
    "cggaacaagaaaaaaanaac",
    "caaahcaaaaaghaaaaaac",
    "caaaeegaaageehaaaggc",
    "..cgeegeeegeeeakjf..",
    "...fhhgeeeghhekkhf..",
    "...fhjeeeeehhefff...",
    "..bbffeeeeeeff.bbb..",
    "..bdddffffff..b..b..",
    ".bdddddfddhfbbd...b.",
    ".bddddfh..hhfd..d.b.",
    ".bdbdah....khfd.d.b.",
    "bd.bfhh....kkhf..d.b",
    "bdfhhf.....feeff.b.b",
    "bdfhhflliiifeefbbb.b",
    "bddffddd...bff...bdb",
    "bdb.bdd...kkkf...bdb",
    "bbb.b...ffjkkf....bb",
    "....fiia..fiif......",
    "....fff....fjf......",
    "....fff....fia......",
    "....ff.....ff......."
   ]
  }
 },
 "dragonet": {
  "w": 29,
  "h": 25,
  "pal": {
   "a": "#35784f",
   "b": "#a9ca7a",
   "c": "#6bae3f",
   "d": "#f6caaa",
   "e": "#9a8394",
   "f": "#1f444f",
   "g": "#e0d6d2",
   "h": "#f49966",
   "i": "#ae9a9d",
   "j": "#bd5227",
   "k": "#eae68d",
   "l": "#b04311",
   "m": "#ebeaea",
   "n": "#e07242",
   "p": "#8cb469",
   "q": "#7a3a2d",
   "M": "#6e3a34"
  },
  "grid": [
   ".........mmaaaaaaaa..........",
   "........accbbbbbbabba........",
   "....aa.abcbbbbbbbbbbba.......",
   "...accacbcbkkbckbkkbbaaaa....",
   "..ecccabbcbbkkckkckkcabbba...",
   ".eggcacbbdcbbbdcbcbaabbbbge..",
   "eggegaccdddcbbddccbbbbgb.g.e.",
   "iee.eaacddhdbbhddcbbaage.i..e",
   ".....aaaddqdddqddccbcca.i.iii",
   "......fahhdddddhhaacccf......",
   ".....faafnddddddaafafff......",
   ".....fafffffllnnafff.........",
   ".....ff.ff..lhhjff...........",
   "...........jddhhl............",
   "..........egg...gi...........",
   "..........egg...gi...........",
   "..........jddddhime..........",
   ".........jddhddhim.e.........",
   "........eggeie...iddl..ppp...",
   "........egggee...ajj....c.c..",
   ".........lhhj.lhjaaa....c.c..",
   "..........jhl.lhdjaaaacc..cc.",
   "..........jhl..jdjacccb..m.c.",
   "..........ige..igi.aaccb..c..",
   "...........ee...ii...aaaaa..."
  ],
  "variants": {
   "eat": [
    ".........mmaaaaaaaa..........",
    "........accbbbbbbabba........",
    "....aa.abcbbbbbbbbbbba.......",
    "...accacbcbkkbckbkkbbaaaa....",
    "..ecccabbcbbkkckkckkcabbba...",
    ".eggcacbbdcbbbdcbcbaabbbbge..",
    "eggegaccdddcbbddccbbbbgb.g.e.",
    "iee.eaacddhdbbhddcbbaage.i..e",
    ".....aaaddqdddqddccbcca.i.iii",
    "......fahhdMMddhhaacccf......",
    ".....faafnddMdddaafafff......",
    ".....fafffffllnnafff.........",
    ".....ff.ff..lhhjff...........",
    "...........jddhhl............",
    "..........egg...gi...........",
    "..........egg...gi...........",
    "..........jddddhime..........",
    ".........jddhddhim.e.........",
    "........eggeie...iddl..ppp...",
    "........egggee...ajj....c.c..",
    ".........lhhj.lhjaaa....c.c..",
    "..........jhl.lhdjaaaacc..cc.",
    "..........jhl..jdjacccb..m.c.",
    "..........ige..igi.aaccb..c..",
    "...........ee...ii...aaaaa..."
   ],
   "flap": [
    ".........mmaaaaaaaa..........",
    "........accbbbbbbabba........",
    "....aa.abcbbbbbbbbbbba.......",
    "..eaccacbcbkkbckbkkbbaaaa....",
    ".egcccabbcbbkkckkckkcabbbae..",
    "egggcacbbdcbbbdcbcbaabbbbg.e.",
    "ieeegaccdddcbbddccbbbbgb.g..e",
    "....eaacddhdbbhddcbbaage.i...",
    ".....aaaddqdddqddccbcca.i.iii",
    "......fahhdddddhhaacccf......",
    ".....faafnddddddaafafff......",
    ".....fafffffllnnafff.........",
    ".....ff.ff..lhhjff...........",
    "...........jddhhl............",
    "..........egg...gi...........",
    "..........egg...gi...........",
    "..........jddddhime..........",
    ".........jddhddhim.e.........",
    "........eggeie...iddl..ppp...",
    "........egggee...ajj....c.c..",
    ".........lhhj.lhjaaa....c.c..",
    "..........jhl.lhdjaaaacc..cc.",
    "..........jhl..jdjacccb..m.c.",
    "..........ige..igi.aaccb..c..",
    "...........ee...ii...aaaaa..."
   ]
  }
 },
 "tanuki": {
  "w": 21,
  "h": 27,
  "pal": {
   "a": "#5d2103",
   "b": "#713c0b",
   "c": "#361102",
   "d": "#f9ca98",
   "e": "#bf632d",
   "f": "#f9a16c",
   "g": "#e1cfcc",
   "h": "#90431b",
   "i": "#a17e6a",
   "j": "#a65523",
   "k": "#86af18",
   "l": "#de7e42",
   "m": "#ef9051",
   "n": "#7c8f24",
   "M": "#5a2a20"
  },
  "grid": [
   "........knnk.........",
   "..ccc..kkkk..ccc.....",
   ".cfaccckkkacccafc....",
   ".cffabbbbbbaafffc....",
   ".cfabbbbbbbbaafac....",
   ".aaabbbbbbbbbaaa.....",
   ".aaabbbbebbbbaac.....",
   "aaaaabbbeebbbaacc....",
   "cajlaaaaaeebbcccc....",
   "ccddmdddmddaaddc.....",
   ".cddadddaddadmmb.....",
   ".affadddaffddmmh.....",
   ".affdddddfflhcc......",
   "..aeddddddecccc......",
   ".aaaajllljcccccc.....",
   "......i..i...........",
   ".....igg.jb..........",
   "....bjbjjjgi.........",
   "....bebjjhg.i........",
   "...bhegjjbh..i.......",
   "...hh.g.hbhjddj......",
   "..i...g..ggjddj......",
   ".i....g...ggej...aaa.",
   ".iiiddbhddhaa...aaaaa",
   "....beb.bebaahjaaaaaa",
   ".....cc..cc.gaeaaeeba",
   ".....cc..cc...bbaab.."
  ],
  "variants": {
   "eat": [
    "........knnk.........",
    "..ccc..kkkk..ccc.....",
    ".cfaccckkkacccafc....",
    ".cffabbbbbbaafffc....",
    ".cfabbbbbbbbaafac....",
    ".aaabbbbbbbbbaaa.....",
    ".aaabbbbebbbbaac.....",
    "aaaaabbbeebbbaacc....",
    "cajlaaaaaeebbcccc....",
    "ccddmdddmddaaddc.....",
    ".cddadddaddadmmb.....",
    ".affadddaffddmmh.....",
    ".affdMMMdfflhcc......",
    "..aeddMdddecccc......",
    ".aaaajllljcccccc.....",
    "......i..i...........",
    ".....igg.jb..........",
    "....bjbjjjgi.........",
    "....bebjjhg.i........",
    "...bhegjjbh..i.......",
    "...hh.g.hbhjddj......",
    "..i...g..ggjddj......",
    ".i....g...ggej...aaa.",
    ".iiiddbhddhaa...aaaaa",
    "....beb.bebaahjaaaaaa",
    ".....cc..cc.gaeaaeeba",
    ".....cc..cc...bbaab.."
   ],
   "flap": [
    "........knnk.........",
    "..ccc..kkkk..ccc.....",
    ".cfaccckkkacccafc....",
    ".cffabbbbbbaafffc....",
    ".cfabbbbbbbbaafac....",
    ".aaabbbbbbbbbaaa.....",
    ".aaabbbbebbbbaac.....",
    "aaaaabbbeebbbaacc....",
    "cajlaaaaaeebbcccc....",
    "ccddmdddmddaaddc.....",
    ".cddadddaddadmmb.....",
    ".affadddaffddmmh.....",
    ".affdddddfflhcc......",
    "..aeddddddecccc......",
    ".aaaajllljcccccc.....",
    "......i..i...........",
    ".....igg.jb..........",
    "....bjbjjjgi.........",
    "....bebjjhg.ii.......",
    "...bhegjjbhjddj......",
    "...hh.g.hbhjddj......",
    "..i...g..gggej...aaa.",
    ".i....g...gaa...aaaaa",
    ".iiiddbhddhaahjaaaaaa",
    "....beb.beb.gaeaaeeba",
    ".....cc..cc...bbaab..",
    ".....cc..cc.........."
   ]
  }
 },
 "elf": {
  "w": 21,
  "h": 28,
  "pal": {
   "a": "#de9977",
   "b": "#967a5c",
   "c": "#944318",
   "d": "#735237",
   "e": "#070606",
   "f": "#8a2c03",
   "g": "#8d6342",
   "h": "#d8d1ce",
   "i": "#2b2830",
   "j": "#d55929",
   "k": "#c96742",
   "l": "#d17f53",
   "m": "#682b19",
   "n": "#531202",
   "p": "#f6bf1f"
  },
  "grid": [
   ".......ddddddd.......",
   ".....ddbbbbbbbdd.....",
   "....dgbbbbbbbbbbd....",
   "...dggbbbbbbbbbbgd...",
   "...dgaabbbbaaabbgd...",
   "...daaajjjjaaaaggd...",
   "...daaajjjjaaaagdd...",
   "cccdaaaaaaaaaaaddcfch",
   "cllfaaaaaaaaaaadaaach",
   ".clfaamaaaamaaakkac..",
   "..ffllmaaaamllakfp...",
   "...fkkaaaaaallaf.p...",
   "....ffaaaaaaaff......",
   ".....bfffjjjfbb......",
   "....ghhhjjja...g.....",
   "....ghhhaaa....g.....",
   ".....nnhaaa.cfm......",
   ".....nffaaacccf......",
   "....nnffaaacccff.....",
   "...nnffaaaaaccfcf....",
   "..ghnffaaaaaccfchg...",
   "..ghbhheeeee..b..g...",
   "...fkeiieeeeiiaam....",
   "....feiieh.eiimm.....",
   ".....eie....eie......",
   ".....eie....eie......",
   ".....eie....eie......",
   ".....ee......ee......"
  ],
  "variants": {
   "eat": [
    ".......ddddddd.......",
    ".....ddbbbbbbbdd.....",
    "....dgbbbbbbbbbbd....",
    "...dggbbbbbbbbbbgd...",
    "...dgaabbbbaaabbgd...",
    "...daaajjjjaaaaggd...",
    "...daaajjjjaaaagdd...",
    "cccdaaaaaaaaaaaddcfch",
    "cllfaaaaaaaaaaadaaach",
    ".clfaamaaaamaaakkac..",
    "..ffllmaaaamllakfp...",
    "...fkkaaffaallaf.p...",
    "....ffaaffaaaff......",
    ".....bfffjjjfbb......",
    "....ghhhjjja...g.....",
    "....ghhhaaa....g.....",
    ".....nnhaaa.cfm......",
    ".....nffaaacccf......",
    "....nnffaaacccff.....",
    "...nnffaaaaaccfcf....",
    "..ghnffaaaaaccfchg...",
    "..ghbhheeeee..b..g...",
    "...fkeiieeeeiiaam....",
    "....feiieh.eiimm.....",
    ".....eie....eie......",
    ".....eie....eie......",
    ".....eie....eie......",
    ".....ee......ee......"
   ],
   "flap": [
    ".......ddddddd.......",
    ".....ddbbbbbbbdd.....",
    "....dgbbbbbbbbbbd....",
    "...dggbbbbbbbbbbgd...",
    "...dgaabbbbaaabbgd...",
    "...daaajjjjaaaaggd...",
    "cccdaaajjjjaaaagddfch",
    "clldaaaaaaaaaaaddcach",
    ".clfaaaaaaaaaaadaac..",
    "..ffaamaaaamaaakka...",
    "...fllmaaaamllakfp...",
    "...fkkaaaaaallaf.p...",
    "....ffaaaaaaaff......",
    ".....bfffjjjfbb......",
    "....ghhhjjja...g.....",
    "....ghhhaaa....g.....",
    ".....nnhaaa.cfm......",
    ".....nffaaacccf......",
    "....nnffaaacccff.....",
    "...nnffaaaaaccfcf....",
    "..ghnffaaaaaccfchg...",
    "..ghbhheeeee..b..g...",
    "...fkeiieeeeiiaam....",
    "....feiieh.eiimm.....",
    ".....eie....eie......",
    ".....eie....eie......",
    ".....eie....eie......",
    ".....ee......ee......"
   ]
  }
 },
 "oni": {
  "w": 26,
  "h": 25,
  "pal": {
   "a": "#3a5163",
   "b": "#070721",
   "c": "#282d41",
   "d": "#cb504c",
   "e": "#f7b72e",
   "f": "#5e1916",
   "g": "#972d21",
   "h": "#43747f",
   "i": "#ac5124",
   "j": "#171c33",
   "k": "#ceb0ab",
   "l": "#c6641b",
   "m": "#4b474c",
   "n": "#bd4238"
  },
  "grid": [
   ".....ccaaaabbbb...........",
   "...ccaaaacccbccj..........",
   "..c.accaaaaac.ajj.........",
   "..c.kcaaacaak.aaj.........",
   ".cckkahacchhkkhaac........",
   ".caajahhcaahcahhac........",
   "caaagaaagaaacaaaab........",
   "jaacgddddddddaaacb........",
   "baacddbdddbddaaacb........",
   "bbbcggbdddbggaaacb........",
   "..bcggdddddggaaajb........",
   "..bccgddddddfaaacb........",
   "..bccbbffffffaaacb........",
   ".bcccbbbbeeeiaaacb........",
   ".bcccbbbbiieeaaccb........",
   ".bccbbbbieeeeejjcc........",
   "...bbbbbfnnnfieei.....aaa.",
   "...bbbb.fnnngfeeei....aaaa",
   "...bb...leeeefeeif....caac",
   "........leeeegfdnf.....ccc",
   "........leeegggff.......b.",
   "........fffffdgf.b......b.",
   ".......fggf.fdb...bb...b..",
   ".......bbb..bbb.....bbb...",
   ".......mm...mm............"
  ],
  "variants": {
   "eat": [
    ".....ccaaaabbbb...........",
    "...ccaaaacccbccj..........",
    "..c.accaaaaac.ajj.........",
    "..c.kcaaacaak.aaj.........",
    ".cckkahacchhkkhaac........",
    ".caajahhcaahcahhac........",
    "caaagaaagaaacaaaab........",
    "jaacgddddddddaaacb........",
    "baacddbdddbddaaacb........",
    "bbbcggbdddbggaaacb........",
    "..bcggdfffdggaaajb........",
    "..bccgddfdddfaaacb........",
    "..bccbbffffffaaacb........",
    ".bcccbbbbeeeiaaacb........",
    ".bcccbbbbiieeaaccb........",
    ".bccbbbbieeeeejjcc........",
    "...bbbbbfnnnfieei.....aaa.",
    "...bbbb.fnnngfeeei....aaaa",
    "...bb...leeeefeeif....caac",
    "........leeeegfdnf.....ccc",
    "........leeegggff.......b.",
    "........fffffdgf.b......b.",
    ".......fggf.fdb...bb...b..",
    ".......bbb..bbb.....bbb...",
    ".......mm...mm............"
   ],
   "flap": [
    ".....ccaaaabbbb...........",
    "...ccaaaacccbccj..........",
    "..c.accaaaaac.ajj.........",
    "..c.kcaaacaak.aaj.........",
    ".cckkahacchhkkhaac........",
    ".caajahhcaahcahhac........",
    "caaagaaagaaacaaaab........",
    "jaacgddddddddaaacb........",
    "baacddbdddbddaaacb........",
    "bbbcggbdddbggaaacb........",
    "..bcggdddddggaaajb........",
    "..bccgddddddfaaacb........",
    "..bccbbffffffaaacb........",
    ".bcccbbbbeeeiaaacb........",
    ".bcccbbbbiieeaaccb........",
    ".bccbbbbieeeeejjcc....aaa.",
    "...bbbbbfnnnfieeii....aaaa",
    "...bbbb.fnnngfeeef....caac",
    "...bb...leeeefeeif.....ccc",
    "........leeeegfdn.......b.",
    "........leeegggffb......b.",
    "........fffffdgf..bb...b..",
    ".......fggf.fdb.....bbb...",
    ".......bbb..bbb...........",
    ".......mm...mm............"
   ]
  }
 },
 "plain": {
  "w": 21,
  "h": 28,
  "pal": {
   "a": "#1a130e",
   "b": "#3d3f31",
   "c": "#944028",
   "d": "#f7ccb2",
   "e": "#5f6a80",
   "f": "#f5ae90",
   "g": "#e08763",
   "h": "#ee9c73",
   "i": "#b8cfc3",
   "j": "#514b43",
   "k": "#000000",
   "l": "#2c2722",
   "m": "#b8b2ae",
   "M": "#5a3226"
  },
  "grid": [
   "........aa...........",
   ".......aaa...........",
   "......aaaa...........",
   "....jaabbbbaabj......",
   "....aabbbbbbbbba...aa",
   "..aaabbbbbbaabbjaaaaa",
   ".abbbbbaabbbaabbbbbba",
   "abbbbbaabbbbaaabbbbaa",
   "abbbbbabbbbaaaabbbaa.",
   "ababbaabbaaffaabbaa..",
   "aaabbaaaaahfdaaaaaa..",
   "..aaffadddldddhhc....",
   "...ahhadddahhdhc.....",
   "...chhdddddhhaa......",
   "....ccddddddaa.......",
   "......cccccc.........",
   "........e..e.........",
   ".......b..lie........",
   "......ababbbae.......",
   ".....bllabbbbaim.....",
   "....e.iaaaaabbahc....",
   "...cddcaaaabbbahc....",
   "...cddca..ibiicc.....",
   "....cc.cffcchhc......",
   ".......cdc.chhc......",
   "......e..e.eie.......",
   "......e.e..eie.......",
   "......kkm..kkm......."
  ],
  "variants": {
   "eat": [
    "........aa...........",
    ".......aaa...........",
    "......aaaa...........",
    "....jaabbbbaabj......",
    "....aabbbbbbbbba...aa",
    "..aaabbbbbbaabbjaaaaa",
    ".abbbbbaabbbaabbbbbba",
    "abbbbbaabbbbaaabbbbaa",
    "abbbbbabbbbaaaabbbaa.",
    "ababbaabbaaffaabbaa..",
    "aaabbaaaaahfdaaaaaa..",
    "..aaffadddldddhhc....",
    "...ahhadddahhdhc.....",
    "...chhdMMMdhhaa......",
    "....ccddMdddaa.......",
    "......cccccc.........",
    "........e..e.........",
    ".......b..lie........",
    "......ababbbae.......",
    ".....bllabbbbaim.....",
    "....e.iaaaaabbahc....",
    "...cddcaaaabbbahc....",
    "...cddca..ibiicc.....",
    "....cc.cffcchhc......",
    ".......cdc.chhc......",
    "......e..e.eie.......",
    "......e.e..eie.......",
    "......kkm..kkm......."
   ],
   "blink": [
    "........aa...........",
    ".......aaa...........",
    "......aaaa...........",
    "....jaabbbbaabj......",
    "....aabbbbbbbbba...aa",
    "..aaabbbbbbaabbjaaaaa",
    ".abbbbbaabbbaabbbbbba",
    "abbbbbaabbbbaaabbbbaa",
    "abbbbbabbbbaaaabbbaa.",
    "ababbaabbaaffaabbaa..",
    "aaabbaaaaahfdaaaaaa..",
    "..aaffddddddddhhc....",
    "...ahhdddddhhdhc.....",
    "...chhdddddhhaa......",
    "....ccddddddaa.......",
    "......cccccc.........",
    "........e..e.........",
    ".......b..lie........",
    "......ababbbae.......",
    ".....bllabbbbaim.....",
    "....e.iaaaaabbahc....",
    "...cddcaaaabbbahc....",
    "...cddca..ibiicc.....",
    "....cc.cffcchhc......",
    ".......cdc.chhc......",
    "......e..e.eie.......",
    "......e.e..eie.......",
    "......kkm..kkm......."
   ]
  }
 },
 "bee": {
  "w": 23,
  "h": 28,
  "pal": {
   "a": "#422106",
   "b": "#ca8621",
   "c": "#895221",
   "d": "#b96435",
   "e": "#9b4213",
   "f": "#7a2e07",
   "g": "#186071",
   "h": "#2791a1",
   "i": "#f2be50",
   "j": "#dbbbbb",
   "k": "#0e0401",
   "l": "#063a44",
   "m": "#cca7a9",
   "n": "#854e4e",
   "p": "#b7847f"
  },
  "grid": [
   "...ccc............ccc..",
   "...cca............acc..",
   ".....aa..aaaaa...aa....",
   "......aaacbbbbccaa.....",
   "......acbbbbbbbbcc.....",
   ".....cbbbbbbbbbbbcc....",
   "....cbbbcbbbebbbbbc....",
   "...ccibbcbbbeebbiibc...",
   ".cccbiiciicdddiibcbbn..",
   "cccabbbcbeddddbbbacbbc.",
   "...abbbeedddddbbcaaaccc",
   "...acbbekdddkdbbeeaa...",
   "...aaceekdddkebbeea....",
   "...aaaeedddddebeaa.....",
   "...aa.aaddddddeaaa.....",
   "...a....aafffaa.aa.....",
   ".........ghhhgl..aa....",
   ".......ggghhhggl...a...",
   "......flgghhhggl...aa..",
   "......aeaddddeeaa..aa..",
   ".....adeaddddeeaea.a...",
   "....addf.m..jjjneea....",
   "....addap..pnnjneea....",
   ".....faf..paajjaaa.....",
   "......a...f.ajja.......",
   ".....f...mf.ajja.......",
   ".....ffaaa..aaaa.......",
   "......ff......aa......."
  ],
  "variants": {
   "eat": [
    "...ccc............ccc..",
    "...cca............acc..",
    ".....aa..aaaaa...aa....",
    "......aaacbbbbccaa.....",
    "......acbbbbbbbbcc.....",
    ".....cbbbbbbbbbbbcc....",
    "....cbbbcbbbebbbbbc....",
    "...ccibbcbbbeebbiibc...",
    ".cccbiiciicdddiibcbbn..",
    "cccabbbcbeddddbbbacbbc.",
    "...abbbeedddddbbcaaaccc",
    "...acbbekdddkdbbeeaa...",
    "...aaceekdddkebbeea....",
    "...aaaeedkkkdebeaa.....",
    "...aa.aaddkdddeaaa.....",
    "...a....aafffaa.aa.....",
    ".........ghhhgl..aa....",
    ".......ggghhhggl...a...",
    "......flgghhhggl...aa..",
    "......aeaddddeeaa..aa..",
    ".....adeaddddeeaea.a...",
    "....addf.m..jjjneea....",
    "....addap..pnnjneea....",
    ".....faf..paajjaaa.....",
    "......a...f.ajja.......",
    ".....f...mf.ajja.......",
    ".....ffaaa..aaaa.......",
    "......ff......aa......."
   ],
   "blink": [
    "...ccc............ccc..",
    "...cca............acc..",
    ".....aa..aaaaa...aa....",
    "......aaacbbbbccaa.....",
    "......acbbbbbbbbcc.....",
    ".....cbbbbbbbbbbbcc....",
    "....cbbbcbbbebbbbbc....",
    "...ccibbcbbbeebbiibc...",
    ".cccbiiciicdddiibcbbn..",
    "cccabbbcbeddddbbbacbbc.",
    "...abbbeedddddbbcaaaccc",
    "...acbbeddddddbbeeaa...",
    "...aaceedddddebbeea....",
    "...aaaeedddddebeaa.....",
    "...aa.aaddddddeaaa.....",
    "...a....aafffaa.aa.....",
    ".........ghhhgl..aa....",
    ".......ggghhhggl...a...",
    "......flgghhhggl...aa..",
    "......aeaddddeeaa..aa..",
    ".....adeaddddeeaea.a...",
    "....addf.m..jjjneea....",
    "....addap..pnnjneea....",
    ".....faf..paajjaaa.....",
    "......a...f.ajja.......",
    ".....f...mf.ajja.......",
    ".....ffaaa..aaaa.......",
    "......ff......aa......."
   ]
  }
 },
 "cow": {
  "w": 21,
  "h": 30,
  "pal": {
   "a": "#810700",
   "b": "#390100",
   "c": "#e1916b",
   "d": "#d6c3c2",
   "e": "#679b38",
   "f": "#ab8e91",
   "g": "#aa3003",
   "h": "#295b57",
   "i": "#c95929",
   "j": "#f0eced",
   "k": "#90b35f",
   "l": "#43756c",
   "m": "#a7b976",
   "n": "#d57346",
   "p": "#941c09",
   "q": "#b5adaa"
  },
  "grid": [
   ".......df............",
   "......df.........df..",
   ".....dff........df...",
   ".....df........ddf...",
   "....ddf.......jdf....",
   "....ddffbbaaaaddf....",
   "....ddffbggggfddf....",
   "....fffbggaaaffff....",
   "....aaagggggaafffa...",
   "...heaeegjjeeaageeh..",
   "..hejjeeedjeeeedjehh.",
   "..hb.daaeeaaaeejjaeh.",
   ".fabbcnpabnpaaaabbb..",
   "aggbbccbcccbccbbbbga.",
   "bbbbaiibcccbiiabbggga",
   "...aaiiccccciiaabbbbb",
   "...aaaiccccccpaabba..",
   "...aabbggggggbaabba..",
   "...aabbbbcccbbaabbaa.",
   "..baabbblddklaabbbba.",
   ".bbbaabbkkkkcgbbbbbaa",
   "bbbq.bbeeeeeeeedbbbaa",
   "bbb.bbkeeemeeedlhbaaa",
   ".bbbblkeeemeddhicaaa.",
   "....hd...jddhhpccaa..",
   "....hlhhlhhhia.aa....",
   "......anna.aia.......",
   ".......aca.acca......",
   ".......aca..pca......",
   ".......qia..fga......"
  ],
  "variants": {
   "eat": [
    ".......df............",
    "......df.........df..",
    ".....dff........df...",
    ".....df........ddf...",
    "....ddf.......jdf....",
    "....ddffbbaaaaddf....",
    "....ddffbggggfddf....",
    "....fffbggaaaffff....",
    "....aaagggggaafffa...",
    "...heaeegjjeeaageeh..",
    "..hejjeeedjeeeedjehh.",
    "..hb.daaeeaaaeejjaeh.",
    ".fabbcnpabnpaaaabbb..",
    "aggbbccbcccbccbbbbga.",
    "bbbbaiibcccbiiabbggga",
    "...aaiicbbbciiaabbbbb",
    "...aaaiccbcccpaabba..",
    "...aabbggggggbaabba..",
    "...aabbbbcccbbaabbaa.",
    "..baabbblddklaabbbba.",
    ".bbbaabbkkkkcgbbbbbaa",
    "bbbq.bbeeeeeeeedbbbaa",
    "bbb.bbkeeemeeedlhbaaa",
    ".bbbblkeeemeddhicaaa.",
    "....hd...jddhhpccaa..",
    "....hlhhlhhhia.aa....",
    "......anna.aia.......",
    ".......aca.acca......",
    ".......aca..pca......",
    ".......qia..fga......"
   ],
   "blink": [
    ".......df............",
    "......df.........df..",
    ".....dff........df...",
    ".....df........ddf...",
    "....ddf.......jdf....",
    "....ddffbbaaaaddf....",
    "....ddffbggggfddf....",
    "....fffbggaaaffff....",
    "....aaagggggaafffa...",
    "...heaeegjjeeaageeh..",
    "..hejjeeedjeeeedjehh.",
    "..hb.daaeeaaaeejjaeh.",
    ".fabbcnpabnpaaaabbb..",
    "aggbbccbcccbccbbbbga.",
    "bbbbaiiccccciiabbggga",
    "...aaiiccccciiaabbbbb",
    "...aaaiccccccpaabba..",
    "...aabbggggggbaabba..",
    "...aabbbbcccbbaabbaa.",
    "..baabbblddklaabbbba.",
    ".bbbaabbkkkkcgbbbbbaa",
    "bbbq.bbeeeeeeeedbbbaa",
    "bbb.bbkeeemeeedlhbaaa",
    ".bbbblkeeemeddhicaaa.",
    "....hd...jddhhpccaa..",
    "....hlhhlhhhia.aa....",
    "......anna.aia.......",
    ".......aca.acca......",
    ".......aca..pca......",
    ".......qia..fga......"
   ]
  }
 }
}

/** Grid + palette for one character; falls back to the base grid when the variant is missing. */
export function castGrid(name: CastName, variant?: CastVariant | null): { rows: Grid; palette: Palette } {
  const s = CAST[name]
  const rows = (variant && s.variants[variant]) || s.grid
  return { rows, palette: s.pal }
}
